common:
  app:
    url: "%env(APP_URL)%"
    name: "HGG ICC-Umstellung"
    version: "1.0.0"
    project_url: ~
    logo: "%env(APP_LOGO)%"
    small_logo: "%env(APP_SMALLLOGO)%"
  locales:
    - de
  menu: mainMenu
  disable:
    saml: true
    cron: true
    mail: true