doctrine:
    dbal:
        default_connection: icc
        connections:
            icc:
                url: '%env(resolve:ICC_DATABASE_URL)%'
                server_version: '5.7'
                charset: utf8mb4
                driver: pdo_mysql
            idp:
                url: '%env(resolve:IDP_DATABASE_URL)%'
                server_version: '5.7'
                charset: utf8mb4
                driver: pdo_mysql
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
